name: Deploying infra on multi cloud

on:
  push:
    branches: [ main ]

jobs:
  azure_job:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout code"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1  

      - name: "azure login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Run Azure CLI Command"
        run: |
          az account show
          az group list
      
      - name: "Terraform Actions -- initializing and validating"
        run: |
          terraform init
          terraform validate
      
      - name: "Terraform Actions--plan"
        run: terraform plan
      - name: Apply Changes
        run: terraform apply --auto-approve

  # aws_job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "checkout code"
  #       uses: actions/checkout@v4

  #     - name: "Setup Terraform"
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: 1.13.1
  #     # Authenticate to Cloud
  #     - name: "Configure to AWS"
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  #         aws-region: ${{secrets.AWS_REGION}}
